
CREATE TABLE IF NOT EXISTS supplier (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(32) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS product_category (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(32) NOT NULL,
  description varchar(300) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS customer (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  first_name varchar(32) NOT NULL,
  last_name varchar(32) NOT NULL,
  username varchar(32) NOT NULL,
  password varchar(60) NOT NULL,
  email_address varchar(32) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE (username),
  UNIQUE (password),
  UNIQUE (email_address)
);

CREATE TABLE IF NOT EXISTS location (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(32) NOT NULL,
  address_country varchar(32) NOT NULL,
  address_city varchar(32) NOT NULL,
  address_county varchar(32) NOT NULL,
  address_street_address varchar(100) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS revenue (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  date date NOT NULL,
  sum decimal NOT NULL,
  location_id int NOT NULL,
  FOREIGN KEY (location_id)
  REFERENCES location (id),
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS product (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(100) NOT NULL,
  description varchar(500) NOT NULL,
  price decimal NOT NULL,
  weight double precision NOT NULL,
  category_id int NOT NULL,
  image_url varchar(300) NULL,
  supplier_id int NOT NULL,
  FOREIGN KEY (category_id)
  REFERENCES product_category (id),
  FOREIGN KEY (supplier_id)
  REFERENCES supplier (id),
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS order_table (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  location_id int NOT NULL,
  customer_id int NOT NULL,
  created_at timestamp NOT NULL,
  address_country varchar(32) NOT NULL,
  address_city varchar(32) NOT NULL,
  address_county varchar(32) NOT NULL,
  address_street_address varchar(100) NOT NULL,
  FOREIGN KEY (location_id)
  REFERENCES location (id),
  FOREIGN KEY (customer_id)
  REFERENCES customer (id),
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS stock (
  product_id bigint NOT NULL,
  location_id bigint NOT NULL,
  quantity int NOT NULL,
  FOREIGN KEY (product_id)
  REFERENCES product (id),
  FOREIGN KEY (location_id)
  REFERENCES location (id),
  PRIMARY KEY (
    product_id,
    location_id
  )
);

CREATE TABLE IF NOT EXISTS order_detail (
  product_id bigint NOT NULL,
  order_id bigint NOT NULL,
  quantity int NOT NULL,
  FOREIGN KEY (product_id)
  REFERENCES product (id),
  FOREIGN KEY (order_id)
  REFERENCES order_table (id),
  PRIMARY KEY (
    product_id,
    order_id
  )
);

